import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as THREE from '../web/vendor/three.module.js';
import {GLTFLoader} from '../web/vendor/GLTFLoader.js';
import {PlayerState,createPlayerState,replacePlayerState} from '../web/player-state.js';
import {GameClock,MissionSystem,ShopSystem,SaveSystem,validateSave,isOpen,timeText} from '../web/game-systems.js';
import {InteractionSystem} from '../web/interaction.js';
import {NavigationNetwork,pointWalkable,segmentWalkable} from '../web/navigation.js';
import {cityWorld} from '../web/city.js';
import {Avatar} from '../web/avatar.js';
import {MovementController,CHARACTER_STATES} from '../web/movement.js';
import {LOCATIONS,NPCS} from '../web/life-data.js';
const loader=new GLTFLoader();loader.register(()=>({name:'headless-textures',loadTexture:()=>Promise.resolve(null)}));
async function glb(name){const b=fs.readFileSync(new URL('../web/assets/'+name,import.meta.url));return loader.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}
let checks=0;function check(value,message){assert.ok(value,message);checks++;}
const player=createPlayerState(),clock=new GameClock(player),shop=new ShopSystem(player),missions=new MissionSystem(player);
check(player.money===500&&player.hp===100&&player.stamina===100,'starting economy');
check(Object.keys(CHARACTER_STATES).length===6,'state interfaces include future vehicles');
missions.accept('new-life');player.area='city';Object.assign(player.position,{x:0,z:-2});missions.updateLocation();check(missions.step.kind==='reach','leave spawn');Object.assign(player.position,LOCATIONS.shop);missions.updateLocation();missions.event('talk',{npc:'npc-clothier'});check(missions.step.kind==='own','talk at clothing store');shop.grant(['street-top','city-bottom']);shop.equip('street');missions.updateLocation();player.area='home';missions.updateLocation();check(player.money===800&&player.mission.completed.includes('new-life'),'first mission pays exactly once');missions.updateLocation();assert.throws(()=>missions.accept('new-life'));check(player.money===800,'completed quest cannot be replayed');
missions.accept('delivery');check(!missions.event('deliver',{npc:'npc-recipient'}),'cannot deliver before collecting');player.inventory.push('parcel');missions.event('pickup',{item:'parcel'});missions.event('deliver',{npc:'npc-recipient'});check(player.money===1300&&!player.inventory.includes('parcel'),'delivery consumes parcel and pays');check(!missions.event('deliver',{npc:'npc-recipient'}),'duplicate delivery cannot pay');
missions.accept('nightlife');player.area='city';Object.assign(player.position,LOCATIONS.night);clock.skipTo(12);missions.updateLocation();check(missions.step.kind==='night','daytime cannot start nightlife');clock.skipTo(18);missions.updateLocation();missions.event('talk',{npc:'npc-night'});check(player.money===1500&&player.mission.completed.length===3,'all three quests complete');
clock.skipTo(0);assert.throws(()=>shop.buy('city-bag'));clock.skipTo(12);shop.buy('city-bag');check(player.money===1420&&player.ownedItems.includes('city-bag'),'purchase debits money and owns item');assert.throws(()=>shop.buy('city-bag'));check(player.money===1420,'duplicate purchase cannot debit');shop.buy('night-dress');shop.equip('night');check(player.outfit.shoes==='black-heels'&&player.outfit.dress==='night-dress','owned outfit equips');shop.equipSlot('top','street-top');check(player.outfit.dress===null,'top removes dress conflict');shop.equipSlot('shoes',null);check(player.outfit.shoes===null,'barefoot slot');assert.throws(()=>shop.equipSlot('top','city-bag'));const poor=createPlayerState();poor.money=1;assert.throws(()=>new ShopSystem(poor).buy('night-dress'));check(poor.money===1&&!poor.ownedItems.includes('night-dress'),'insufficient funds transaction is atomic');
check(isOpen(8*60)&&!isOpen(20*60)&&isOpen(0,18,6)&&!isOpen(12*60,18,6),'opening hours wrap midnight');player.timeMinutes=1439;clock.update(2);check(timeText(player.timeMinutes)==='00:02','continuous clock wraps');
const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},saves=new SaveSystem(storage);player.hp=0;saves.save(player);player.money=1400;saves.save(player);let loaded=saves.load();check(loaded.hp===0&&loaded.money===1400,'save restores zero HP and economy');check(memory.size===2,'two save slots alternate');const newest=[...memory].sort((a,b)=>JSON.parse(b[1]).stamp-JSON.parse(a[1]).stamp)[0];memory.set(newest[0],'corrupt');check(saves.load().money===1120,'corrupt newest slot falls back');check(validateSave({...player,position:{x:NaN,y:0,z:0,yaw:0}})===null,'invalid location rejected');assert.throws(()=>new SaveSystem({...storage,setItem:()=>{throw new Error('Quota');}}).save(player));check(saves.load()!==null,'failed save does not overwrite good slot');const reference=PlayerState;replacePlayerState(PlayerState,loaded);check(PlayerState===reference&&PlayerState.money===1400,'central state identity remains stable');
const interaction=new InteractionSystem(player);let called=0;interaction.register({id:'a',area:'home',position:{x:0,z:0},interact:p=>{check(p===player,'interaction receives central player');called++;}});player.area='city';player.position.x=player.position.z=0;check(interaction.interact()===null&&called===0,'area isolation');player.area='home';interaction.interact();check(called===1,'unified interaction');player.position.x=10;interaction.interact();check(called===1,'distance guard');
const city=await glb('city-neighborhood.glb'),world=cityWorld(city),nav=new NavigationNetwork(world);check(nav.nodes.length>100,'waypoint network generated');let paths=0;
for(const target of [...Object.values(LOCATIONS),...NPCS]){check(pointWalkable(world,target.x,target.z),`target is outside buildings ${JSON.stringify(target)}`);const route=nav.path(LOCATIONS.citySpawn,target);check(route.length>0,'mission and NPC targets are reachable');let previous=LOCATIONS.citySpawn;for(const next of route){check(segmentWalkable(world,previous,next),'no navigation segment cuts a building');previous=next;}paths++;}
for(let i=0;i<80;i++){const a=nav.nodes[(i*31)%nav.nodes.length],b=nav.randomNear(a,30,()=>((i*23)%101)/101),route=nav.path(a,b);if(!route.length)continue;let previous=a;for(const next of route){check(segmentWalkable(world,previous,next),'random waypoint routes avoid buildings');previous=next;}}
let poses=0,minimumFoot=Infinity,maximumLift=0;const allNames=['Idle_Heels','Walk_Heels','Run_Heels','Rifle_Aim_Idle'];
for(const filename of ['jill-barefoot-locomotion.glb','jill-heels-locomotion.glb']){
 const g=await glb(filename),controller=new MovementController(),avatar=new Avatar(g,controller),actor=new THREE.Group();actor.add(avatar.root);const weightsList=[];for(const a of allNames){weightsList.push(Object.fromEntries(allNames.map(n=>[n,Number(n===a)])));for(const b of allNames)if(a<b)weightsList.push(Object.fromEntries(allNames.map(n=>[n,n===a||n===b?.5:0])));}
 for(const weights of weightsList)for(let i=0;i<33;i++){actor.position.set(0,0,0);avatar.update(weights,i/33,i*.071);actor.updateMatrixWorld(true);avatar.ground(actor,()=>0,0);check(Number.isFinite(avatar.clearance)&&avatar.clearance>-.002,'feet do not penetrate ground');minimumFoot=Math.min(minimumFoot,avatar.clearance);maximumLift=Math.max(maximumLift,actor.position.y);for(const bone of avatar.foot.skeleton.bones)check(bone.matrixWorld.elements.every(Number.isFinite),'finite animation bones');poses++;}
 for(const outfit of [{top:'street-top',bottom:'city-bottom'},{dress:'night-dress',shoes:'black-heels'}]){avatar.outfit(outfit);check(avatar.clothes.top.visible===!!outfit.top&&avatar.clothes.dress.visible===!!outfit.dress,'clothing visibility follows central slots');}
 check(avatar.foot.skeleton.bones.length>=191,'original full skeleton retained');
}
console.log(JSON.stringify({status:'passed',checks,missions:3,npcDefinitions:NPCS.length,navigationNodes:nav.nodes.length,reachableTargets:paths,animationPoses:poses,minimumFootClearanceM:minimumFoot,maximumGroundLiftM:maximumLift,dualSlotSave:true},null,2));
