// Actual skinning, terrain and migration regressions for this asset update.
import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import * as T from '../web/vendor/three.module.js';import {GLTFLoader} from '../web/vendor/GLTFLoader.js';import {Avatar} from '../web/avatar.js';import {MovementController} from '../web/movement.js';import {OUTFITS,NPCS} from '../web/life-data.js';import {createPlayerState} from '../web/player-state.js';import {ShopSystem,validateSave} from '../web/game-systems.js';import {cityWorld,groundSampler,cameraFraction} from '../web/city.js';import {pointWalkable,NavigationNetwork,segmentWalkable} from '../web/navigation.js';
const loader=new GLTFLoader();loader.register(()=>({name:'headless-textures',loadTexture:()=>Promise.resolve(null)}));
async function glb(name){const b=fs.readFileSync(new URL('../web/assets/'+name,import.meta.url));return loader.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}
const wardrobe=JSON.parse(fs.readFileSync(new URL('../models/new-wardrobe-manifest.json',import.meta.url))),female=JSON.parse(fs.readFileSync(new URL('../web/assets/npcs/female-manifest.json',import.meta.url)));
for(const [name,record] of Object.entries(wardrobe.assets)){const b=fs.readFileSync(new URL('../web/assets/'+name,import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),record.sha256);assert.equal(b.length,record.byteLength);}
assert.equal(NPCS.length,12);assert.equal(NPCS.filter(n=>n.gender==='female').length,6);
const legacy=createPlayerState();delete legacy.cityScale;legacy.area='city';legacy.position={x:12,y:.09,z:-10,yaw:1.2};legacy.money=913;legacy.mission.completed=['delivery'];const migrated=validateSave(legacy);assert.equal(migrated.money,913);assert.equal(migrated.position.yaw,1.2);assert.ok(Math.abs(migrated.position.x-19.2)<1e-8&&Math.abs(migrated.position.z+16)<1e-8);assert.deepEqual(migrated.mission.completed,['delivery']);assert.ok(migrated.ownedItems.includes('city-dress')&&migrated.ownedItems.includes('dorsay-shoes'));
const shopPlayer=createPlayerState(),shop=new ShopSystem(shopPlayer);shop.equip('dress-dorsay');shop.equipSlot('shoes','ada-shoes');assert.equal(shopPlayer.outfit.dress,'city-dress');assert.equal(shopPlayer.outfit.shoes,'ada-shoes');shop.equipSlot('shoes',null);assert.equal(shopPlayer.outfit.dress,'city-dress');assert.equal(shopPlayer.outfit.shoes,null);
const assets={top:await glb('ada-top.glb'),shoes:await glb('ada-shoes.glb'),dorsay:await glb('dorsay-shoes.glb'),dress:await glb('city-dress.glb')},clips=['Idle_Heels','Walk_Heels','Run_Heels','Rifle_Aim_Idle'],v=new T.Vector3();let clothingPoses=0,minimumShoe=Infinity;
for(const [variant,outfits] of [['heels',['ada-set','dorsay-set','dress-dorsay']],['barefoot',['dress-only']]]){
 const avatar=new Avatar(await glb('jill-'+variant+'-locomotion.glb'),new MovementController(),assets),actor=new T.Group();actor.add(avatar.root);const body=avatar.attachments.body,original=avatar.attachments.fullPosition.array.slice();
 for(const id of outfits){avatar.outfit(OUTFITS.find(o=>o.id===id).slots);for(const clip of clips)for(let i=0;i<30;i++){
  actor.position.set(0,0,0);avatar.update(Object.fromEntries(clips.map(n=>[n,Number(n===clip)])),i/30,i*.083);actor.updateMatrixWorld(true);avatar.ground(actor,()=>0,0);
  for(const item of avatar.attachments.items.values())for(const mesh of item.meshes)if(mesh.visible){const p=mesh.geometry.attributes.position;let low=Infinity;for(let k=0;k<p.count;k+=item.slot==='shoes'?1:7){v.fromBufferAttribute(p,k);mesh.applyBoneTransform(k,v);mesh.localToWorld(v);assert.ok(v.toArray().every(Number.isFinite));low=Math.min(low,v.y);}if(item.slot==='shoes'){minimumShoe=Math.min(minimumShoe,low);assert.ok(low>-.003,'shoe under ground at '+id+' '+clip+' '+i);}}
  assert.deepEqual(actor.scale.toArray(),[1,1,1]);clothingPoses++;
 }}avatar.outfit(OUTFITS.find(o=>o.id==='original').slots);assert.deepEqual(body.geometry.attributes.position.array,original);assert.equal(body.geometry.index,avatar.attachments.fullIndex);
}
let npcPoses=0,minFoot=Infinity,maxHeight=0,maxWidth=0;
for(const record of female.citizens){
 const bytes=fs.readFileSync(new URL('../web/'+record.path,import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),record.sha256);const g=await glb(record.path.replace('assets/',''));assert.equal(g.parser.json.skins.length,1);assert.equal(g.parser.json.skins[0].joints.length,57);assert.ok(record.heightMetres>1.68&&record.heightMetres<1.73);
 const mixer=new T.AnimationMixer(g.scene),meshes=[];g.scene.traverse(n=>{if(n.isSkinnedMesh)meshes.push(n);});
 for(const clip of g.animations){mixer.stopAllAction();mixer.clipAction(clip).reset().play();for(let f=0;f<65;f++){
  mixer.setTime(clip.duration*f/65);g.scene.updateMatrixWorld(true);let low=Infinity,high=-Infinity,minX=Infinity,maxX=-Infinity;
  for(const m of meshes){const p=m.geometry.attributes.position;for(let k=0;k<p.count;k++){if(k%9&&p.getY(k)>.07)continue;v.fromBufferAttribute(p,k);m.applyBoneTransform(k,v);m.localToWorld(v);assert.ok(v.toArray().every(Number.isFinite));low=Math.min(low,v.y);high=Math.max(high,v.y);minX=Math.min(minX,v.x);maxX=Math.max(maxX,v.x);}}
  assert.ok(high<1.95&&maxX-minX<1.6,'NPC bone pivot mismatch '+record.id+' '+clip.name);assert.ok(low>-.008&&low<.025,'NPC feet contact ground');minFoot=Math.min(minFoot,low);maxHeight=Math.max(maxHeight,high);maxWidth=Math.max(maxWidth,maxX-minX);npcPoses++;
 }}
}
const city=await glb('city-neighborhood.glb'),district=await glb('city-east-district.glb'),world=cityWorld(city,district),ground=groundSampler(city.scene),nav=new NavigationNetwork(world);assert.equal(world.scale,.72);assert.equal(world.district.scale,1.6);for(const n of NPCS)assert.ok(pointWalkable(world,n.x,n.z));assert.ok(Math.abs(ground(245,0))<.015);const eastRoute=nav.path({x:0,z:3.52},{x:245,z:0});assert.ok(eastRoute.length>0);let previous={x:0,z:3.52};for(const p of eastRoute){assert.ok(segmentWalkable(world,previous,p));previous=p;}const fraction=cameraFraction(world,{x:241,y:1,z:0},{x:236,y:1.4,z:0});assert.ok(fraction>0&&fraction<1,'east district camera wall protection');
const report={status:'passed',clothingPoses,npcPoses,minimumShoeClearanceM:minimumShoe,minimumNPCFootM:minFoot,maximumNPCHeightM:maxHeight,maximumNPCWidthM:maxWidth,npcCount:12,femaleCount:6,cityScale:.72,cityPositionMigration:true,eastDistrictReachable:true,originalBodyRestored:true};console.log(JSON.stringify(report,null,2));
