// Three viewpoints of the exact extracted GLB. No generated replacement asset.
import {createServer} from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const sharp=(await import(process.env.SHARP_MODULE||'sharp')).default;
const root=path.resolve(fileURLToPath(new URL('../web/',import.meta.url)));
const output=path.resolve(process.env.HEELS_OUTPUT||'artifacts/life-v1/jill-high-heels-preview.png');await fs.mkdir(path.dirname(output),{recursive:true});
const html=`<!doctype html><html><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#c4d3d3}canvas{width:100%;height:100%}</style><canvas></canvas><script type="module">
import * as T from '/vendor/three.module.js';import {GLTFLoader} from '/vendor/GLTFLoader.js';
const renderer=new T.WebGLRenderer({canvas:document.querySelector('canvas'),antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color('#c4d3d3');scene.add(new T.HemisphereLight('#ffffff','#697a80',2.4));const sun=new T.DirectionalLight('#ffffff',3);sun.position.set(.7,1.1,.65);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-.7,right:.7,top:.7,bottom:-.7,near:.01,far:3});sun.shadow.bias=-.00004;scene.add(sun);
const fill=new T.DirectionalLight('#d6efff',1.1);fill.position.set(-1,.5,-.5);scene.add(fill);
const floor=new T.Mesh(new T.PlaneGeometry(3,3),new T.MeshStandardMaterial({color:'#c4d3d3',roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const g=await new GLTFLoader().loadAsync('/assets/jill-high-heels.glb');const box=new T.Box3().setFromObject(g.scene);g.scene.position.y=-box.min.y;g.scene.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;}});scene.add(g.scene);
const camera=new T.PerspectiveCamera(35,innerWidth/innerHeight,.001,10);window.view=(position)=>{camera.position.fromArray(position);camera.lookAt(0,.104,0);renderer.render(scene,camera);};window.view([.38,.31,.53]);window.ready=true;window.stats={meshes:g.parser.json.meshes.length,skins:g.parser.json.skins?.length||0,height:box.max.y-box.min.y};
</script></html>`;
const server=createServer(async(req,res)=>{try{if(req.url==='/'){res.writeHead(200,{'Content-Type':'text/html'});res.end(html);return;}const filename=path.resolve(root,'.'+req.url);if(!filename.startsWith(root+path.sep))throw new Error();const bytes=await fs.readFile(filename);res.writeHead(200,{'Content-Type':filename.endsWith('.js')?'text/javascript':'application/octet-stream','Content-Length':bytes.length});res.end(bytes);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:640,height:620}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.ready);const views=[[.38,.31,.53],[.65,.22,-.035],[-.36,.26,-.53]],parts=[];for(const position of views){await page.evaluate(p=>window.view(p),position);parts.push(await page.screenshot());}const labels=['三分之四视角','侧面 · 鞋跟','后侧 · 鞋底'];const svg=Buffer.from(`<svg width="1920" height="760" xmlns="http://www.w3.org/2000/svg"><rect width="1920" height="760" fill="#c4d3d3"/><g fill="#1d363e" font-family="Noto Sans CJK SC,sans-serif"><text x="40" y="52" font-size="26">JILL · 独立高跟鞋</text><text x="40" y="83" font-size="14">原模型提取 / 保留原材质与米制比例 / 无人物身体网格</text>${labels.map((label,i)=>`<text x="${i*640+34}" y="732" font-size="20">${label}</text>`).join('')}</g></svg>`);await sharp(svg).composite(parts.map((input,i)=>({input,left:i*640,top:94}))).png().toFile(output);const stats=await page.evaluate(()=>window.stats);if(errors.length)throw new Error(errors.join('\n'));console.log(JSON.stringify({output,...stats,errors}));}finally{await browser?.close();server.close();}
