// Real Three.js wardrobe and female-citizen renders, with all supplied materials.
import {createServer} from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright'),sharp=(await import(process.env.SHARP_MODULE||'sharp')).default;
const root=path.resolve(fileURLToPath(new URL('../web/',import.meta.url))),output=path.resolve(process.env.PREVIEW_OUTPUT||'artifacts/city-clothes');await fs.mkdir(output,{recursive:true});
const html=`<html><style>body{margin:0;background:#c6ced7}</style><canvas></canvas><script type="module">
import * as T from '/vendor/three.module.js';import {GLTFLoader} from '/vendor/GLTFLoader.js';import {Avatar} from '/avatar.js';import {MovementController} from '/movement.js';import {OUTFITS} from '/life-data.js';import {usesHeelPosture} from '/wardrobe-attachments.js';
const renderer=new T.WebGLRenderer({canvas:document.querySelector('canvas'),antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;const scene=new T.Scene();scene.background=new T.Color('#c6ced7');scene.add(new T.HemisphereLight('#ffffff','#7b8390',2.3));const sun=new T.DirectionalLight('#fff3e9',3);sun.position.set(2.5,4,3.5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-6,right:6,top:3,bottom:-2,near:.1,far:16});sun.shadow.bias=-.00005;scene.add(sun);const fill=new T.DirectionalLight('#e1edff',1.6);fill.position.set(-3,2,-2);scene.add(fill);const floor=new T.Mesh(new T.PlaneGeometry(30,30),new T.MeshStandardMaterial({color:'#c6ced7',roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const actor=new T.Group(),npcGroup=new T.Group();scene.add(actor,npcGroup);const camera=new T.PerspectiveCamera(32,innerWidth/innerHeight,.01,50),loader=new GLTFLoader();
const [bare,heels,top,shoes,dorsay,dress]=await Promise.all(['jill-barefoot-locomotion','jill-heels-locomotion','ada-top','ada-shoes','dorsay-shoes','city-dress'].map(n=>loader.loadAsync('/assets/'+n+'.glb')));const controller=new MovementController(),assets={top,shoes,dorsay,dress},avatars={barefoot:new Avatar(bare,controller,assets),heels:new Avatar(heels,controller,assets)};actor.add(avatars.barefoot.root,avatars.heels.root);
window.pose=(id,clip='Idle_Heels',phase=0,elapsed=0)=>{actor.visible=true;npcGroup.visible=false;const outfit=OUTFITS.find(o=>o.id===id),active=usesHeelPosture(outfit.slots.shoes)?avatars.heels:avatars.barefoot;for(const a of Object.values(avatars)){a.root.visible=a===active;a.outfit(outfit.slots);}actor.position.set(0,0,0);active.update(Object.fromEntries(['Idle_Heels','Walk_Heels','Run_Heels','Rifle_Aim_Idle'].map(n=>[n,Number(n===clip)])),phase,elapsed);actor.updateMatrixWorld(true);active.ground(actor,()=>0,0);return {outfit:id,scale:actor.scale.toArray(),parts:active.attachments.snapshot(),clearance:active.clearance};};
window.view=name=>{const views={front:[[1.65,1.14,3.45],[0,.87,0]],back:[[-1.65,1.14,-3.45],[0,.87,0]],shoeFront:[[.50,.27,.62],[0,.10,0]],shoeBack:[[-.5,.31,-.62],[0,.11,0]]};const [p,t]=views[name];camera.fov=name.startsWith('shoe')?28:32;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();camera.position.fromArray(p);camera.lookAt(...t);renderer.render(scene,camera);};
window.citizens=async(clip='Citizen_Idle',phase=.3)=>{renderer.setSize(innerWidth,innerHeight);actor.visible=false;npcGroup.visible=true;if(!npcGroup.children.length)for(let i=1;i<=6;i++){const g=await loader.loadAsync('/assets/npcs/female-citizen-'+String(i).padStart(2,'0')+'.glb'),mixer=new T.AnimationMixer(g.scene);g.scene.position.x=(i-3.5)*.9;g.scene.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;n.frustumCulled=false;}});g.scene.userData={mixer,clips:g.animations};npcGroup.add(g.scene);}for(const n of npcGroup.children){const {mixer,clips}=n.userData;mixer.stopAllAction();const c=T.AnimationClip.findByName(clips,clip);mixer.clipAction(c).play();mixer.setTime(c.duration*phase);}camera.fov=32;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();camera.position.set(.2,1.4,6.3);camera.lookAt(0,.88,0);renderer.render(scene,camera);};window.pose('dress-dorsay');window.view('front');window.ready=true;
</script></html>`;
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root+path.sep))throw Error('path');const bytes=await fs.readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'application/octet-stream');res.end(bytes);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:760,height:1000}}),errors=[],records=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready,null,{timeout:120000});
 for(const [id,title,file,views] of [['ada-set','黑色高跟鞋 · 鞋口与后跟修正','ada-heels-fixed.png',['shoeFront','shoeBack']],['dorsay-set','D’Orsay 高跟鞋 · 实际穿着','dorsay-heels-preview.png',['front','shoeFront']],['dress-dorsay','上传连衣裙＋D’Orsay 高跟鞋','dress-heels-preview.png',['front','back']]]){
  records.push(await page.evaluate(id=>window.pose(id),id));const parts=[];for(const v of views){await page.evaluate(v=>window.view(v),v);parts.push(await page.screenshot());}const svg=Buffer.from('<svg width="1520" height="1140" xmlns="http://www.w3.org/2000/svg"><rect width="1520" height="1140" fill="#c6ced7"/><g fill="#263a49" font-family="Noto Sans CJK SC,sans-serif"><text x="42" y="50" font-size="29">'+title+'</text><text x="42" y="82" font-size="16">真实游戏模型 / Jill 原始尺寸 / 独立衣柜部件</text></g></svg>');await sharp(svg).composite(parts.map((input,i)=>({input,left:i*760,top:96}))).png().toFile(path.join(output,file));console.log(file);
 }
 if(process.env.POSE_QA==='1')for(const outfit of ['ada-set','dorsay-set','dress-dorsay'])for(const clip of ['Walk_Heels','Run_Heels','Rifle_Aim_Idle']){await page.evaluate(p=>window.pose(...p),[outfit,clip,.28,.28]);await page.evaluate(v=>window.view(v),outfit==='dress-dorsay'?'front':'shoeFront');await page.screenshot({path:path.join(output,outfit+'-'+clip+'.png')});}
 await page.setViewportSize({width:1600,height:720});const rows=[],labels=['待机 · Standing Idle','行走 · Dwarf Walk','对话 · 与男性市民相同的 Citizen_Talk'];
 for(const [i,clip] of ['Citizen_Idle','Citizen_Walk','Citizen_Talk'].entries()){await page.evaluate(c=>window.citizens(c),clip);const input=await page.screenshot();rows.push(await sharp(input).extract({left:0,top:100,width:1600,height:530}).png().toBuffer());if(process.env.POSE_QA==='1')await fs.writeFile(path.join(output,clip+'.png'),input);}
 const labelsSvg=Buffer.from('<svg width="1600" height="1870" xmlns="http://www.w3.org/2000/svg"><rect width="1600" height="1870" fill="#c6ced7"/><g fill="#263a49" font-family="Noto Sans CJK SC,sans-serif"><text x="42" y="48" font-size="30">女性市民 · 6 个独立模型</text><text x="42" y="80" font-size="17">真实骨架动画 / 身高约 1.69～1.71 米 / 与 Jill 1.73 米保持同一单位</text>'+labels.map((s,i)=>'<text x="42" y="'+(126+i*575)+'" font-size="24">'+s+'</text>').join('')+'</g></svg>');await sharp(labelsSvg).composite(rows.map((input,i)=>({input,left:0,top:142+i*575}))).png().toFile(path.join(output,'female-citizens-preview.png'));
 if(errors.length)throw Error(errors.join('\n'));await fs.writeFile(path.join(output,'render-check.json'),JSON.stringify({status:'passed',records,errors},null,2)+'\n');console.log(JSON.stringify({status:'passed',records,errors}));
}finally{await browser?.close();server.close();}
