import * as THREE from './vendor/three.module.js';
import {WardrobeAttachments} from './wardrobe-attachments.js';
const CLIPS=['Idle_Heels','Walk_Heels','Run_Heels','Rifle_Aim_Idle'];
function clothingGeometry(rings,bones){const positions=[],joints=[],weights=[],indices=[];const count=32;for(let r=0;r<rings.length;r++){const ring=rings[r];for(let k=0;k<count;k++){const a=k/count*Math.PI*2;positions.push(ring.rx*Math.cos(a),ring.y,ring.z+ring.rz*Math.sin(a));joints.push(bones[ring.bone],0,0,0);weights.push(1,0,0,0);if(r){const p=(r-1)*count+k,q=(r-1)*count+(k+1)%count,t=r*count+k,u=r*count+(k+1)%count;indices.push(p,t,q,q,t,u);}}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(joints,4));g.setAttribute('skinWeight',new THREE.Float32BufferAttribute(weights,4));g.setIndex(indices);g.computeVertexNormals();return g;}
export class Avatar{
 constructor(gltf,controller,wardrobeAssets=null){this.root=gltf.scene;this.controller=controller;this.mixer=new THREE.AnimationMixer(this.root);this.actions={};this.v=new THREE.Vector3();this.left=new THREE.Vector3();this.right=new THREE.Vector3();this.clearance=0;this.anchor=null;this.clothes={};
  for(const name of CLIPS){const clip=THREE.AnimationClip.findByName(gltf.animations,name);if(!clip)throw new Error(`缺少动画 ${name}`);const action=this.mixer.clipAction(clip);action.play();action.setEffectiveWeight(name==='Idle_Heels'?1:0);this.actions[name]={action,duration:clip.duration};}
  this.root.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;n.frustumCulled=false;}});this.root.updateMatrixWorld(true);
  const body=this.root.getObjectByName('Bodyspine_2'),head=this.root.getObjectByName('Headspine_2');if(body&&head)this.anchor={body,head,offset:body.matrixWorld.clone().invert().multiply(head.matrixWorld),local:new THREE.Matrix4()};
  this.foot=this.root.getObjectByName('Bodypl2020_Boots_Mat')||this.root.getObjectByName('pl2020_Skin_Mat');if(!this.foot?.isSkinnedMesh)throw new Error('人物缺少脚部蒙皮');const position=this.foot.geometry.getAttribute('position');this.soleIndices=[];for(let i=0;i<position.count;i++)if(position.getY(i)<.055&&i%3===0)this.soleIndices.push(i);if(!this.soleIndices.length)throw new Error('人物脚底采样为空');
  const walk=gltf.parser.json.animations.find(a=>a.name==='Walk_Heels')?.extras?.referenceStrideDistance,run=gltf.parser.json.animations.find(a=>a.name==='Run_Heels')?.extras?.referenceStrideDistance;if(walk>0)controller.setWalkReference(walk);if(run>0)controller.setRunReference(run);this.makeClothes();if(wardrobeAssets)this.attachments=new WardrobeAttachments(this,wardrobeAssets);
 }
 makeClothes(){const skin=this.root.getObjectByName('BodySkin_Mat')||this.root.getObjectByName('pl2020_Skin_Mat'),skeleton=skin.skeleton;const names=['hips','spine_0','spine_1','spine_2'];const bones=Object.fromEntries(names.map(name=>[name,skeleton.bones.findIndex(b=>b.name===name||b.name==='Body'+name)]));if(Object.values(bones).some(i=>i<0))throw new Error('服装绑定骨架不完整');const source=skin.geometry.getAttribute('position');
  const ring=(y,bone,minimumRx=.14)=>{let rx=minimumRx,minZ=-.13,maxZ=.17;for(let i=0;i<source.count;i++){const x=source.getX(i),z=source.getZ(i);if(Math.abs(source.getY(i)-y)<.055&&Math.abs(x)<.25){rx=Math.max(rx,Math.abs(x)+.02);minZ=Math.min(minZ,z-.022);maxZ=Math.max(maxZ,z+.024);}}return {y,bone,rx:Math.min(rx,.265),z:(minZ+maxZ)/2,rz:(maxZ-minZ)/2};};
  const top=[ring(1.01,'hips'),ring(1.13,'spine_0'),ring(1.27,'spine_1'),ring(1.4,'spine_2'),{...ring(1.46,'spine_2'),rx:.15}];
  const skirt=[{y:.60,bone:'hips',rx:.28,z:.105,rz:.33},{y:.78,bone:'hips',rx:.235,z:.105,rz:.33},{...ring(.99,'hips'),rx:.19,rz:.3,z:.11}];
  const dress=[{y:.55,bone:'hips',rx:.29,z:.11,rz:.34},...skirt.slice(1),...top.slice(1)];
  for(const [name,rings,color] of [['top',top,'#38959e'],['bottom',skirt,'#263a51'],['dress',dress,'#4d356b']]){const mesh=new THREE.SkinnedMesh(clothingGeometry(rings,bones),new THREE.MeshStandardMaterial({color,roughness:.9,side:THREE.DoubleSide}));mesh.bind(skeleton,new THREE.Matrix4());mesh.name='TestClothing_'+name;mesh.castShadow=true;mesh.receiveShadow=true;mesh.frustumCulled=false;mesh.visible=false;this.root.add(mesh);this.clothes[name]=mesh;}
  const bagGeometry=new THREE.BoxGeometry(.16,.22,.075);bagGeometry.translate(.27,.96,-.015);const count=bagGeometry.attributes.position.count;const ji=[],we=[];for(let i=0;i<count;i++){ji.push(bones.hips,0,0,0);we.push(1,0,0,0);}bagGeometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(ji,4));bagGeometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(we,4));const bag=new THREE.SkinnedMesh(bagGeometry,new THREE.MeshStandardMaterial({color:'#b3754f',roughness:.92}));bag.bind(skeleton,new THREE.Matrix4());bag.visible=false;bag.castShadow=true;this.root.add(bag);this.clothes.accessory=bag;
 }
 outfit(value){const procedural={top:'street-top',bottom:'city-bottom',dress:'night-dress',accessory:'city-bag'};for(const [name,mesh] of Object.entries(this.clothes))mesh.visible=value[name]===procedural[name];this.attachments?.outfit(value);}
 update(weights,phase,elapsed){for(const [name,{action,duration}] of Object.entries(this.actions)){action.time=name==='Walk_Heels'||name==='Run_Heels'?phase*duration:elapsed%duration;action.setEffectiveWeight(weights[name]);}this.mixer.update(0);this.root.updateMatrixWorld(true);if(this.anchor){const {body,head,offset,local}=this.anchor;local.copy(head.parent.matrixWorld).invert().multiply(body.matrixWorld).multiply(offset);local.decompose(head.position,head.quaternion,head.scale);head.updateMatrixWorld(true);}}
 ground(parent,sampleGround,groundY){let low=Infinity,left=Infinity,right=Infinity;const pos=this.foot.geometry.attributes.position;for(const i of this.soleIndices){this.v.fromBufferAttribute(pos,i);this.foot.applyBoneTransform(i,this.v);this.foot.localToWorld(this.v);low=Math.min(low,this.v.y);if(pos.getX(i)<0){if(this.v.y<left){left=this.v.y;this.left.copy(this.v);}}else if(this.v.y<right){right=this.v.y;this.right.copy(this.v);}}const lift=Math.max(0,groundY+.001-low,(sampleGround?.(this.left.x,this.left.z)??groundY)+.001-left,(sampleGround?.(this.right.x,this.right.z)??groundY)+.001-right);if(lift){parent.position.y+=lift;parent.updateMatrixWorld(true);}this.clearance=low+lift-groundY;}
}
