import {createPlayerState} from './player-state.js';
import {PRODUCTS,OUTFITS,MISSIONS,LOCATIONS,ADA_STARTER_ITEMS} from './life-data.js';
export function isOpen(minutes,start=8,end=20){const h=((minutes%1440)+1440)%1440/60;return start<end?h>=start&&h<end:h>=start||h<end;}
export function timeText(minutes){const n=Math.floor(((minutes%1440)+1440)%1440);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
export class GameClock{constructor(player){this.player=player;}update(dt){this.player.timeMinutes=(this.player.timeMinutes+dt*1.5)%1440;}skipTo(hour){if(![0,6,12,18].includes(hour))throw new Error('请选择 00、06、12 或 18 点');this.player.timeMinutes=hour*60;this.player.stamina=100;this.player.flags.exhausted=false;}}
export class ShopSystem{
 constructor(player,onChange=()=>{}){this.player=player;this.onChange=onChange;}
 grant(ids){for(const id of ids)if(!this.player.ownedItems.includes(id))this.player.ownedItems.push(id);this.onChange();}
 buy(id){const product=PRODUCTS.find(p=>p.id===id);if(!product)throw new Error('商品不存在');if(!isOpen(this.player.timeMinutes))throw new Error('服装店营业时间 08:00～20:00');if(this.player.ownedItems.includes(id))throw new Error('已经拥有这件物品');if(this.player.money<product.price)throw new Error('金钱不足');this.player.money-=product.price;this.grant([id]);return product;}
 equip(id){const preset=OUTFITS.find(p=>p.id===id);if(!preset||!preset.requires.every(item=>this.player.ownedItems.includes(item)))throw new Error('请先获得对应的服装');Object.assign(this.player.outfit,{preset:id,...preset.slots});this.onChange();return preset;}
 equipSlot(type,id){if(!['top','bottom','shoes','dress','accessory'].includes(type))throw new Error('服装类型无效');const product=PRODUCTS.find(p=>p.id===id&&p.type===type);if(id!==null&&(!product||!this.player.ownedItems.includes(id)))throw new Error('尚未拥有这件物品');this.player.outfit[type]=id;this.player.outfit.preset='custom';if(type==='dress'&&id){this.player.outfit.top=this.player.outfit.bottom=null;}if((type==='top'||type==='bottom')&&id)this.player.outfit.dress=null;this.onChange();}
}
export class MissionSystem{
 constructor(player,onComplete=()=>{}){this.player=player;this.onComplete=onComplete;}
 get active(){return MISSIONS.find(m=>m.id===this.player.mission.activeId)||null;}
 get step(){return this.active?.steps[this.player.mission.progress[this.active.id]||0]||null;}
 accept(id){const m=MISSIONS.find(m=>m.id===id);if(!m)throw new Error('任务不存在');if(this.player.mission.completed.includes(id))throw new Error('任务已经完成');if(this.active&&this.active.id!==id)throw new Error('请先完成当前任务');this.player.mission.activeId=id;this.player.mission.progress[id]??=0;this.updateLocation();return m;}
 advance(){const m=this.active;if(!m)return;const n=(this.player.mission.progress[m.id]||0)+1;this.player.mission.progress[m.id]=n;if(n>=m.steps.length){if(!this.player.mission.completed.includes(m.id)){this.player.mission.completed.push(m.id);this.player.money+=m.reward;this.player.mission.activeId=null;this.onComplete(m);}}}
 event(type,data={}){const s=this.step;if(!s)return false;const matches=s.kind==='talk'&&type==='talk'&&data.npc===s.npc||s.kind==='pickup'&&type==='pickup'&&data.item===s.item||s.kind==='deliver'&&type==='deliver'&&data.npc===s.npc&&this.player.inventory.includes('parcel');if(matches){if(s.kind==='deliver')this.player.inventory=this.player.inventory.filter(i=>i!=='parcel');this.advance();this.updateLocation();return true;}return false;}
 updateLocation(){for(let i=0;i<6;i++){const s=this.step;if(!s)return;const p=this.player.position;let match=false;if(s.kind==='leave')match=this.player.area==='city'&&Math.hypot(p.x-LOCATIONS.citySpawn.x,p.z-LOCATIONS.citySpawn.z)>3;if(s.kind==='reach'||s.kind==='night'){const goal=LOCATIONS[s.location];match=this.player.area==='city'&&Math.hypot(p.x-goal.x,p.z-goal.z)<2.4&&(s.kind!=='night'||isOpen(this.player.timeMinutes,18,6));}if(s.kind==='own')match=s.items.every(id=>this.player.ownedItems.includes(id));if(s.kind==='home')match=this.player.area==='home';if(!match)return;this.advance();}}
 get target(){const s=this.step;if(!s)return null;if(s.kind==='home')return {...LOCATIONS.homeDoor,name:'出生公寓'};if(s.location)return {...LOCATIONS[s.location],name:s.text};if(s.kind==='own'||s.npc==='npc-clothier')return {...LOCATIONS.shop,name:'服装店'};if(s.kind==='pickup')return {...LOCATIONS.parcel,name:'包裹'};if(s.npc==='npc-recipient')return {...LOCATIONS.delivery,name:'阿成'};if(s.npc==='npc-night')return {...LOCATIONS.night,name:'阿墨'};return null;}
}
function checksum(text){let n=2166136261;for(let i=0;i<text.length;i++){n^=text.charCodeAt(i);n=Math.imul(n,16777619);}return (n>>>0).toString(16);}
export function validateSave(data){
 if(!data||data.version!==1||!['home','city'].includes(data.area)||!data.position||!['x','y','z','yaw'].every(k=>Number.isFinite(data.position[k]))||Math.abs(data.position.x)>500||Math.abs(data.position.z)>500||!Number.isInteger(data.money)||data.money<0||data.money>99999999||!Number.isFinite(data.timeMinutes))return null;
 const clean=createPlayerState();clean.money=data.money;clean.area=data.area;clean.position={...data.position};clean.timeMinutes=((data.timeMinutes%1440)+1440)%1440;clean.hp=Math.max(0,Math.min(100,Number.isFinite(data.hp)?data.hp:100));clean.stamina=Math.max(0,Math.min(100,Number(data.stamina)||0));const allowed=new Set(['original',...PRODUCTS.map(p=>p.id)]);clean.ownedItems=[...new Set(['original',...ADA_STARTER_ITEMS,...(Array.isArray(data.ownedItems)?data.ownedItems:[]).filter(i=>allowed.has(i))])];clean.inventory=Array.isArray(data.inventory)?data.inventory.filter(i=>i==='parcel'):[];
 const missionIds=new Set(MISSIONS.map(m=>m.id));clean.mission.completed=Array.isArray(data.mission?.completed)?[...new Set(data.mission.completed.filter(i=>missionIds.has(i)))]:[];for(const m of MISSIONS){const n=data.mission?.progress?.[m.id];if(Number.isInteger(n)&&n>=0&&n<=m.steps.length)clean.mission.progress[m.id]=n;}const active=data.mission?.activeId;if(missionIds.has(active)&&!clean.mission.completed.includes(active))clean.mission.activeId=active;
 const outfit=OUTFITS.find(o=>o.id===data.outfit?.preset&&o.requires.every(id=>clean.ownedItems.includes(id)));if(outfit)clean.outfit={preset:outfit.id,...outfit.slots};else if(data.outfit?.preset==='custom'){clean.outfit.preset='custom';for(const type of ['top','bottom','shoes','dress','accessory']){const item=PRODUCTS.find(p=>p.id===data.outfit[type]&&p.type===type);clean.outfit[type]=item&&clean.ownedItems.includes(item.id)?item.id:null;}}
 if(['low','balanced'].includes(data.settings?.quality))clean.settings.quality=data.settings.quality;if(Number.isFinite(data.settings?.cameraDistance))clean.settings.cameraDistance=Math.max(1.8,Math.min(3.2,data.settings.cameraDistance));return clean;
}
export class SaveSystem{
 constructor(storage){this.storage=storage;this.lastStamp=0;this.nextSlot=0;this.error=null;}
 load(){const candidates=[];try{for(const key of ['luna15.life.v1.a','luna15.life.v1.b']){try{const e=JSON.parse(this.storage.getItem(key));if(e&&typeof e.body==='string'&&e.checksum===checksum(e.body)){const value=validateSave(JSON.parse(e.body));if(value)candidates.push({stamp:e.stamp,value,key});}}catch{}}this.error=null;}catch(e){this.error=e.message;}candidates.sort((a,b)=>b.stamp-a.stamp);this.lastStamp=candidates[0]?.stamp||0;this.nextSlot=candidates[0]?.key==='luna15.life.v1.a'?1:0;return candidates[0]?.value||null;}
 save(player){const value=validateSave(player);if(!value)throw new Error('玩家状态无效，未覆盖存档');const body=JSON.stringify(value),stamp=Math.max(Date.now(),this.lastStamp+1);const envelope=JSON.stringify({stamp,body,checksum:checksum(body)});const key=['luna15.life.v1.a','luna15.life.v1.b'][this.nextSlot];try{this.storage.setItem(key,envelope);this.lastStamp=stamp;this.nextSlot=1-this.nextSlot;this.error=null;return true;}catch(e){this.error=e.message;throw new Error('存档失败，请检查设备剩余空间');}}
 clear(){this.storage.removeItem('luna15.life.v1.a');this.storage.removeItem('luna15.life.v1.b');}
}
