import {PRODUCTS,OUTFITS,MISSIONS,ITEM_TYPES,LOCATIONS} from './life-data.js';
import {timeText,isOpen} from './game-systems.js';
const $=id=>document.getElementById(id);
const button=(action,label,value='',extra='')=>`<button data-action="${action}" data-value="${value}" ${extra}>${label}</button>`;
export class GameUI {
  constructor(player,missions,hooks){this.player=player;this.missions=missions;this.hooks=hooks;this.view=null;this.data=null;this.tab='top';this.toastTimer=null;
    $('panel-content').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;try{if(b.dataset.action==='tab'){this.tab=b.dataset.value;this.render();}else hooks.action(b.dataset.action,b.dataset.value);}catch(error){this.toast(error.message);}});
    $('close-panel').addEventListener('click',()=>this.close());
  }
  toast(message){clearTimeout(this.toastTimer);$('toast').textContent=message;$('toast').hidden=false;this.toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
  open(view,data=null){this.view=view;this.data=data;this.hooks.modal(true);$('modal').hidden=false;this.render();}
  close(){this.view=null;this.data=null;$('modal').hidden=true;this.hooks.modal(false);}
  refresh(){if(this.view)this.render();}
  render(){const p=this.player,m=this.missions;let title='',body='';
    if(this.view==='pause'){title='暂停';body=`<div class="grid">${button('resume','继续游戏')}${button('map','地图')}${button('missions','任务')}${button('wardrobe','衣柜')}${button('settings','设置')}${button('main','返回主菜单')}</div><p class="note">游戏已暂停。WASD 移动 · Shift 跑步 · E 互动</p>`;}
    if(this.view==='missions'){title='街区任务';body=MISSIONS.map(mission=>{const done=p.mission.completed.includes(mission.id),active=p.mission.activeId===mission.id,step=p.mission.progress[mission.id]||0;return `<div class="card"><div><h3>${mission.name} <small>¥ ${mission.reward}</small></h3><p>${done?'已完成':active?mission.steps[step]?.text:'认识街区，完成一件小事。'}</p></div>${button('accept',done?'已完成':active?'进行中':'接取',mission.id,done||active||m.active?'disabled':'')}</div>${active?`<ol class="steps">${mission.steps.map((s,i)=>`<li>${i<step?'✓ ':''}${s.text}</li>`).join('')}</ol>`:''}`;}).join('');}
    if(this.view==='shop'){title='服装店';body=`<p class="note">营业时间 08:00～20:00 · 当前 ${timeText(p.timeMinutes)} · 余额 ¥ ${p.money}</p>`+PRODUCTS.map(item=>`<div class="card"><div><h3>${item.name}</h3><p>${ITEM_TYPES[item.type]} · ¥ ${item.price}</p></div>${button('buy',p.ownedItems.includes(item.id)?'已拥有':'购买',item.id,p.ownedItems.includes(item.id)||p.money<item.price||!isOpen(p.timeMinutes)?'disabled':'')}</div>`).join('')+button('wardrobe','打开衣柜');}
    if(this.view==='wardrobe'){title='衣柜';body=`<p class="note">选择套装，或按部位搭配已有物品。</p><div class="preset-grid">${OUTFITS.map(o=>button('outfit',`${o.name}<small>${p.outfit.preset===o.id?'正在穿着':o.requires.every(id=>p.ownedItems.includes(id))?'点击试穿':'尚未获得'}</small>`,o.id,`aria-pressed="${p.outfit.preset===o.id}" ${o.requires.every(id=>p.ownedItems.includes(id))?'':'disabled'}`)).join('')}</div><div class="tabs">${Object.entries(ITEM_TYPES).map(([id,label])=>button('tab',label,id,`aria-pressed="${this.tab===id}"`)).join('')}</div><div class="row">${button('slot',`不穿${ITEM_TYPES[this.tab]}`,`${this.tab}:none`)}${PRODUCTS.filter(item=>item.type===this.tab&&p.ownedItems.includes(item.id)).map(item=>button('slot',item.name,`${this.tab}:${item.id}`,`aria-pressed="${p.outfit[this.tab]===item.id}"`)).join('')}</div>`;}
    if(this.view==='rest'){title='休息';body=`<p class="dialog-text">回到安全屋，休息一下。体力将恢复。</p><div class="grid">${[6,12,18,0].map(hour=>button('time',`${String(hour).padStart(2,'0')}:00`,String(hour))).join('')}</div>`;}
    if(this.view==='settings'){title='设置';body=`<p class="note">画面质量</p><div class="row">${button('quality','流畅','low',`aria-pressed="${p.settings.quality==='low'}"`)}${button('quality','均衡','balanced',`aria-pressed="${p.settings.quality==='balanced'}"`)}</div><p class="note">第三人称镜头距离</p><div class="row">${[1.8,2.2,2.8].map(n=>button('distance',`${n.toFixed(1)} 米`,String(n),`aria-pressed="${Math.abs(p.settings.cameraDistance-n)<.01}"`)).join('')}</div><p class="note">人物观察</p><div class="row">${button('foot','脚部视角')}${button('reset','回到安全屋')}${button('save','保存游戏')}</div>`;}
    if(this.view==='map'){title='街区地图';body='<div class="map-wrap"><canvas id="city-map" width="900" height="350"></canvas></div><div class="legend"><span><i style="background:#8bddca"></i>玩家</span><span><i style="background:#e6b66b"></i>任务</span><span><i style="background:#9aadc2"></i>地点</span></div><p class="note">上方为北。出生公寓位于中央街口，服装店在北侧。</p>';}
    if(this.view==='dialog'){const n=this.data;title=n.name;let text='今天也是好天气。沿着街道走走吧，北边的服装店很近。',actions='';
      if(n.role==='guide'){text='欢迎来到街区！先去服装店认识阿晴，再回来安顿。需要赚点钱，也可以帮忙送个包裹。';actions=MISSIONS.map(task=>button('accept',task.name,task.id,p.mission.completed.includes(task.id)||m.active?'disabled':'')).join('');}
      if(n.role==='clothier'){text='欢迎！这里可以买服装，也可以试穿自己已有的搭配。新邻居有一套入门服装可以领取。';actions=button('shop','浏览商品')+(m.active?.id==='new-life'&&m.step?.kind==='own'?button('gift','领取入门服装','','class="primary"'):'');}
      if(n.role==='recipient'){text=p.inventory.includes('parcel')?'你把包裹送来了？太好了，谢谢！':'有包裹要送给我，可以在服装店北侧接取。';if(m.active?.id==='delivery'&&p.inventory.includes('parcel'))actions=button('deliver','交付包裹','','class="primary"');}
      if(n.role==='night')text=isOpen(p.timeMinutes,18,6)?'街区安静下来了。欢迎来北街，今晚过得愉快！':'晚上再来吧，18:00 以后我们在这里见面。';
      body=`<p class="dialog-text">${text}</p><div class="row">${actions}${button('resume','结束交谈')}</div>`;
    }
    $('panel-title').textContent=title;$('panel-content').innerHTML=body;if(this.view==='map')this.drawMap();
  }
  drawMap(){const canvas=$('city-map'),ctx=canvas.getContext('2d'),world=this.hooks.world(),b=world.bounds,scale=Math.min((canvas.width-36)/(b.maxX-b.minX),(canvas.height-36)/(b.maxZ-b.minZ)),ox=(canvas.width-(b.maxX-b.minX)*scale)/2,oz=(canvas.height-(b.maxZ-b.minZ)*scale)/2;const x=v=>ox+(v-b.minX)*scale,z=v=>oz+(v-b.minZ)*scale;ctx.fillStyle='#0e242c';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#29434b';for(const o of world.obstacles)ctx.fillRect(x(o.min[0]),z(o.min[2]),(o.max[0]-o.min[0])*scale,(o.max[2]-o.min[2])*scale);ctx.strokeStyle='#476169';ctx.strokeRect(ox,oz,(b.maxX-b.minX)*scale,(b.maxZ-b.minZ)*scale);const dot=(pos,color,r)=>{ctx.beginPath();ctx.fillStyle=color;ctx.arc(x(pos.x),z(pos.z),r,0,Math.PI*2);ctx.fill();};for(const id of ['homeDoor','shop','parcel','night'])dot(LOCATIONS[id],'#9aadc2',4);if(this.missions.target)dot(this.missions.target,'#e6b66b',6);dot(this.player.area==='city'?this.player.position:LOCATIONS.homeDoor,'#8bddca',6);}
  hud(nearest,controller){const p=this.player;$('hp').textContent=Math.round(p.hp);$('stamina').textContent=Math.round(p.stamina);$('hp-fill').style.width=`${p.hp}%`;$('stamina-fill').style.width=`${p.stamina}%`;$('money').textContent=`¥ ${p.money.toLocaleString('en-US')}`;$('game-time').textContent=timeText(p.timeMinutes);$('location').textContent=p.area==='home'?'出生公寓 · 安全屋':'Luna 街区';$('motion-state').textContent=controller.interacting?'互动':controller.state;$('mission-name').textContent=this.missions.active?.name||'在城市开始新生活';$('mission-step').textContent=this.missions.step?.text||(p.area==='home'?'到公寓门口，进入街区':'与街口阿岚交谈，或探索街区');$('interact').hidden=!nearest;$('interact').textContent=nearest?.label||'互动';$('aim').setAttribute('aria-pressed',String(controller.aiming));}
}
