// Walkable rectangle + expanded obstacles + an eight-neighbour waypoint graph.
export function pointWalkable(world,x,z,r=.34){if(x<world.bounds.minX+r||x>world.bounds.maxX-r||z<world.bounds.minZ+r||z>world.bounds.maxZ-r)return false;return !world.obstacles.some(b=>x>b.min[0]-r&&x<b.max[0]+r&&z>b.min[2]-r&&z<b.max[2]+r);}
export function segmentWalkable(world,a,b,r=.34){if(!pointWalkable(world,a.x,a.z,r)||!pointWalkable(world,b.x,b.z,r))return false;for(const box of world.obstacles){let enter=0,exit=1;for(const [key,axis] of [['x',0],['z',2]]){const d=b[key]-a[key],low=box.min[axis]-r,high=box.max[axis]+r;if(Math.abs(d)<1e-8){if(a[key]<=low||a[key]>=high){enter=2;break;}continue;}let p=(low-a[key])/d,q=(high-a[key])/d;if(p>q)[p,q]=[q,p];enter=Math.max(enter,p);exit=Math.min(exit,q);}if(enter<exit&&enter<1&&exit>0)return false;}return true;}
export class NavigationNetwork{
 constructor(world,spacing=3){this.world=world;this.nodes=[];this.grid=new Map();this.spacing=spacing;let row=0;for(let z=world.bounds.minZ+1;z<world.bounds.maxZ-1;z+=spacing,row++){let col=0;for(let x=world.bounds.minX+1;x<world.bounds.maxX-1;x+=spacing,col++)if(pointWalkable(world,x,z)){const node={id:this.nodes.length,x,z,row,col,links:[]};this.nodes.push(node);this.grid.set(`${col},${row}`,node);}}for(const node of this.nodes)for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const next=this.grid.get(`${node.col+dx},${node.row+dz}`);if(next&&segmentWalkable(world,node,next))node.links.push(next.id);}if(!this.nodes.length)throw new Error('街道导航点为空');}
 nearest(point,visibleFrom=null){let best=null,distance=Infinity;for(const node of this.nodes){const d=(node.x-point.x)**2+(node.z-point.z)**2;if(d<distance&&(!visibleFrom||segmentWalkable(this.world,visibleFrom,node))){best=node;distance=d;}}return best;}
 path(from,to){if(segmentWalkable(this.world,from,to))return [{x:to.x,z:to.z}];const start=this.nearest(from,from),end=this.nearest(to,to);if(!start||!end)return [];const open=new Set([start.id]),score=new Map([[start.id,0]]),previous=new Map();const heuristic=id=>Math.hypot(this.nodes[id].x-end.x,this.nodes[id].z-end.z);let found=false;while(open.size){let id=-1,best=Infinity;for(const i of open){const v=score.get(i)+heuristic(i);if(v<best){best=v;id=i;}}if(id===end.id){found=true;break;}open.delete(id);for(const link of this.nodes[id].links){const n=this.nodes[link],cost=score.get(id)+Math.hypot(n.x-this.nodes[id].x,n.z-this.nodes[id].z);if(cost<(score.get(link)??Infinity)){score.set(link,cost);previous.set(link,id);open.add(link);}}}if(!found)return [];const ids=[end.id];while(ids.at(-1)!==start.id)ids.push(previous.get(ids.at(-1)));ids.reverse();const raw=[...ids.map(id=>({x:this.nodes[id].x,z:this.nodes[id].z})),{x:to.x,z:to.z}],result=[];let anchor=from;for(let i=0;i<raw.length;){let j=raw.length-1;while(j>i&&!segmentWalkable(this.world,anchor,raw[j]))j--;result.push(raw[j]);anchor=raw[j];i=j+1;}return result;}
 randomNear(point,radius=24,random=Math.random){const choices=this.nodes.filter(n=>Math.hypot(n.x-point.x,n.z-point.z)<radius&&n.links.length);return choices.length?choices[Math.floor(random()*choices.length)]:this.nearest(point);}
}
