import * as THREE from './vendor/three.module.js';
import {NPCS} from './life-data.js';
import {pointWalkable,segmentWalkable} from './navigation.js';
// Clone rig nodes while sharing their geometry, textures and materials.
export function cloneRig(source){const copy=source.clone(true),original=[],clones=[];source.traverse(n=>original.push(n));copy.traverse(n=>clones.push(n));const map=new Map(original.map((n,i)=>[n,clones[i]]));for(let i=0;i<original.length;i++)if(original[i].isSkinnedMesh){const skin=clones[i];skin.skeleton=original[i].skeleton.clone();skin.skeleton.bones=original[i].skeleton.bones.map(b=>map.get(b));skin.bindMatrix.copy(original[i].bindMatrix);skin.bindMatrixInverse.copy(original[i].bindMatrixInverse);}return copy;}
export class NPCManager{
 constructor(network,player,group,sampleGround){this.network=network;this.player=player;this.group=group;this.sampleGround=sampleGround;this.npcs=[];this.elapsed=0;this.debug={near:0,far:0,hidden:0,invalidPositions:0};}
 async load(loader){const models=new Map();for(const key of [...new Set(NPCS.map(n=>`${n.gender}-${n.model}`))]){const [gender,number]=key.split('-');models.set(key,await loader.loadAsync(`./assets/npcs/${gender}-citizen-${String(number).padStart(2,'0')}.glb`));}for(const definition of NPCS){const gltf=models.get(`${definition.gender}-${definition.model}`),root=cloneRig(gltf.scene),mixer=new THREE.AnimationMixer(root),actions={};for(const name of ['Citizen_Idle','Citizen_Walk','Citizen_Talk']){const clip=THREE.AnimationClip.findByName(gltf.animations,name);if(!clip)throw new Error('NPC 动画不完整');const action=mixer.clipAction(clip);action.play();action.setEffectiveWeight(name==='Citizen_Idle'?1:0);actions[name]={action,duration:clip.duration};}let position={x:definition.x,z:definition.z};if(!pointWalkable(this.network.world,position.x,position.z))position=this.network.nearest(position);root.position.set(position.x,this.sampleGround(position.x,position.z),position.z);root.traverse(n=>{if(n.isMesh){n.castShadow=false;n.receiveShadow=true;n.frustumCulled=true;n.boundingSphere=new THREE.Sphere(new THREE.Vector3(0,.9,0),1.4);}});const stride=gltf.parser.json.animations.find(a=>a.name==='Citizen_Walk').extras.rootMotionRemovedMetres;const npc={...definition,root,mixer,actions,position:{x:position.x,z:position.z},anchor:{x:position.x,z:position.z},state:'Idle',wait:2+Math.random()*4,path:[],phase:Math.random(),elapsed:Math.random()*5,accumulator:0,distance:0,stride:Math.hypot(...stride),weights:{Citizen_Idle:1,Citizen_Walk:0,Citizen_Talk:0}};this.npcs.push(npc);this.group.add(root);}}
 talk(id,enabled){const n=this.npcs.find(n=>n.id===id);if(n){n.state=enabled?'Talk':'Idle';n.wait=2;n.path=[];}}
 get(id){return this.npcs.find(n=>n.id===id);}
 update(dt,talkOnly=false){this.elapsed+=dt;this.debug.near=this.debug.far=this.debug.hidden=0;let shadowCount=0;for(const n of this.npcs){if(talkOnly&&n.state!=='Talk')continue;n.distance=Math.hypot(n.position.x-this.player.position.x,n.position.z-this.player.position.z);if(this.player.area!=='city'||n.distance>80){n.root.visible=false;this.debug.hidden++;continue;}n.root.visible=true;const shadow=n.distance<16&&shadowCount<2;if(shadow)shadowCount++;n.root.traverse(mesh=>{if(mesh.isMesh)mesh.castShadow=shadow;});n.accumulator+=dt;const cadence=n.distance<=40?0:.25;if(cadence){this.debug.far++;if(n.accumulator<cadence)continue;}else this.debug.near++;const step=Math.min(n.accumulator,.35);n.accumulator=0;n.elapsed+=step;let travelled=0;
   if(n.state==='Talk'){const target=Math.atan2(this.player.position.x-n.position.x,this.player.position.z-n.position.z),diff=Math.atan2(Math.sin(target-n.root.rotation.y),Math.cos(target-n.root.rotation.y));n.root.rotation.y+=diff*(1-Math.exp(-step*9));}
   else if(n.state==='Idle'&&n.roam){n.wait-=step;if(n.wait<=0){const destination=this.network.randomNear(n.anchor,25);n.path=this.network.path(n.position,destination);n.state=n.path.length?'WalkTo':'Idle';n.wait=3;}}
   if(n.state==='WalkTo'){let budget=1.2*step;while(budget>0&&n.path.length){const target=n.path[0],dx=target.x-n.position.x,dz=target.z-n.position.z,distance=Math.hypot(dx,dz),advance=Math.min(distance,budget);if(distance<.02){n.path.shift();continue;}const next={x:n.position.x+dx/distance*advance,z:n.position.z+dz/distance*advance};if(!segmentWalkable(this.network.world,n.position,next)){n.path=[];this.debug.invalidPositions++;break;}n.position.x=next.x;n.position.z=next.z;budget-=advance;travelled+=advance;const yaw=Math.atan2(dx,dz),diff=Math.atan2(Math.sin(yaw-n.root.rotation.y),Math.cos(yaw-n.root.rotation.y));n.root.rotation.y+=diff*(1-Math.exp(-step*8));if(advance>=distance-.001)n.path.shift();}if(!n.path.length){n.state='Idle';n.wait=2+Math.random()*6;}}
   n.phase=(n.phase+travelled/n.stride)%1;const target=n.state==='Talk'?'Citizen_Talk':travelled>0?'Citizen_Walk':'Citizen_Idle';for(const [name,v] of Object.entries(n.actions)){n.weights[name]+=(Number(name===target)-n.weights[name])*(1-Math.exp(-step*12));v.action.setEffectiveWeight(n.weights[name]);v.action.time=name==='Citizen_Walk'?n.phase*v.duration:n.elapsed%v.duration;}n.mixer.update(0);n.root.position.set(n.position.x,this.sampleGround(n.position.x,n.position.z),n.position.z);}}
 snapshot(){return this.npcs.map(n=>({id:n.id,name:n.name,gender:n.gender,model:n.model,state:n.state,x:n.position.x,z:n.position.z,distance:n.distance,visible:n.root.visible,pathNodes:n.path.length}));}
}
